window.DIECK_DATA = {
  "ui": {
    "view": "dashboard",
    "mode": "paqueteria",
    "date": "2026-03-29",
    "week": 13,
    "signature": "Supervisor de Producción",
    "historyFilter": {
      "mode": "",
      "from": "",
      "to": "",
      "query": ""
    }
  },
  "master": [
    {
      "codigo": "PT-111-008",
      "descripcion": "ARROZ BAMBI SUPER ECONOMICO SAQ (65/35) 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M2",
      "entero_min": 65,
      "mignon_max": 35,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-111-003",
      "descripcion": "ARROZ BLANCO #3 100 LBS (85/15)",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 85,
      "mignon_max": 15,
      "pulido_min": "41-42",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-111-002",
      "descripcion": "ARROZ BLANCO #2 100 LBS (90/10)",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "41-42",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-003",
      "descripcion": "ARROZ BAMBI ECONOMICO QQ (80/20) 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 80,
      "mignon_max": 20,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-004",
      "descripcion": "ARROZ MR. DIECK ESCALDADO QUINTAL 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M2",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "22-23",
      "tarima_div": 40,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-005",
      "descripcion": "ARROZ MANHATTAN ORO QUINTAL 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M2",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "22-23",
      "tarima_div": 40,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-006",
      "descripcion": "ARROZ BAMBINO ESCALDADO QUINTAL 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M2",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "22-23",
      "tarima_div": 40,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-007",
      "descripcion": "ARROZ MR. DIECK BLANCO QUINTAL 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-008",
      "descripcion": "ARROZ MANHATTAN BLANCO QUINTAL 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-012",
      "descripcion": "ARROZ BAMBI PREMIUM QQ 90/10",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-002",
      "descripcion": "ARROZ BAMBI AZUL SAQUITO 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M2",
      "entero_min": 85,
      "mignon_max": 15,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-003",
      "descripcion": "ARROZ BAMBI ECONOMICO SAQ (80/20) 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M1",
      "entero_min": 80,
      "mignon_max": 20,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-004",
      "descripcion": "ARROZ MR. DIECK ESCALDADO SAQUITO 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M2",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "22-23",
      "tarima_div": 150,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-005",
      "descripcion": "ARROZ MANHATTAN ORO SAQUITO 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M2",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "37-38",
      "tarima_div": 175,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-006",
      "descripcion": "ARROZ MR. DIECK BLANCO SAQUITO 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M1",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "37-38",
      "tarima_div": 175,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-008",
      "descripcion": "ARROZ MANHATTAN BLANCO SAQUITO 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M1",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "37-38",
      "tarima_div": 175,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-101-010",
      "descripcion": "ARROZ BAMBI PREMIUM SAQ 90/10",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M2",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "37-38",
      "tarima_div": 175,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-111-005",
      "descripcion": "ARROZ BAMBI SUPER ECONOMICO QQ (70/30) 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 70,
      "mignon_max": 30,
      "pulido_min": "37-38",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-111-006",
      "descripcion": "ARROZ ESCALDADO #1 100 LBS (A)",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M2",
      "entero_min": 94,
      "mignon_max": 6,
      "pulido_min": "22-23",
      "tarima_div": 40,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-111-008",
      "descripcion": "ARROZ BAMBI SUPER ECONOMICO SAQ (70/30) 25 LBS",
      "peso": 25,
      "unidad": "SAQUITO",
      "familia": "SAQUITO",
      "proceso": "M1",
      "entero_min": 70,
      "mignon_max": 30,
      "pulido_min": "37-38",
      "tarima_div": 175,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-009",
      "descripcion": "ARROZ BLANCO PMA (50 KGS)",
      "peso": 110.25,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M1",
      "entero_min": 80,
      "mignon_max": 20,
      "pulido_min": "37-39",
      "tarima_div": 100,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M1",
      "tipo": "PT"
    },
    {
      "codigo": "PT-102-001",
      "descripcion": "ARROZ MANHATTAN ORO 4 LBS (10)",
      "peso": 40,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 150,
      "bobina_unidades": 10,
      "bobina_rend": 50,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-102-003",
      "descripcion": "ARROZ MANHATTAN BLANCO 4 LBS (10)",
      "peso": 40,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "37-38",
      "tarima_div": 150,
      "bobina_unidades": 10,
      "bobina_rend": 50,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-103-001",
      "descripcion": "ARROZ MR. DIECK ESCALDADO 1.75 KGS (10)",
      "peso": 38.5,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 125,
      "bobina_unidades": 10,
      "bobina_rend": 51,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-103-003",
      "descripcion": "ARROZ MR. DIECK BLANCO 1.75 KGS (10)",
      "peso": 38.5,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "37-38",
      "tarima_div": 125,
      "bobina_unidades": 10,
      "bobina_rend": 51,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-104-001",
      "descripcion": "ARROZ MR. DIECK ESCALDADO 1.5 KGS (10)",
      "peso": 33,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 80,
      "bobina_unidades": 10,
      "bobina_rend": 56,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-104-003",
      "descripcion": "ARROZ MR. DIECK BLANCO 1.5 KGS (10)",
      "peso": 33,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "37-38",
      "tarima_div": 80,
      "bobina_unidades": 10,
      "bobina_rend": 56,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-104-010",
      "descripcion": "ARROZ MANHATTAN ORO 1.5 KGS (10)",
      "peso": 33,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 100,
      "bobina_unidades": 10,
      "bobina_rend": 56,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-104-011",
      "descripcion": "ARROZ MANHATTAN BLANCO 1.5 KGS (10)",
      "peso": 33,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "37-38",
      "tarima_div": 120,
      "bobina_unidades": 10,
      "bobina_rend": 56,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-001",
      "descripcion": "ARROZ MR. DIECK BLANCO 1 LBS (25)",
      "peso": 25,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "37-38",
      "tarima_div": 80,
      "bobina_unidades": 25,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-002",
      "descripcion": "ARROZ MANHATTAN ORO 1 LBS (25)",
      "peso": 25,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 80,
      "bobina_unidades": 25,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-003",
      "descripcion": "ARROZ MANHATTAN BLANCO 1 LBS (25)",
      "peso": 25,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "37-39",
      "tarima_div": 80,
      "bobina_unidades": 25,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-004",
      "descripcion": "ARROZ MANHATTAN BLANCO 1 LBS (20)",
      "peso": 20,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 89,
      "mignon_max": 11,
      "pulido_min": "37-38",
      "tarima_div": 80,
      "bobina_unidades": 20,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-007",
      "descripcion": "ARROZ MR. DIECK INTEGRAL 1 LBS (25)",
      "peso": 25,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 96,
      "mignon_max": 4,
      "pulido_min": "16-18",
      "tarima_div": 80,
      "bobina_unidades": 25,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-010",
      "descripcion": "ARROZ MANHATTAN BLANCO ECONOMICO 400 GRS (20)",
      "peso": 20,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 80,
      "mignon_max": 20,
      "pulido_min": "37-38",
      "tarima_div": 80,
      "bobina_unidades": 20,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-106-011",
      "descripcion": "ARROZ MANHATTAN BLANCO ECONOMICO 400 GRS (20)",
      "peso": 20,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 80,
      "mignon_max": 20,
      "pulido_min": "37-38",
      "tarima_div": 80,
      "bobina_unidades": 20,
      "bobina_rend": 125,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-107-001",
      "descripcion": "ARROZ MR. DIECK ESCALDADO 350 GRS (25)",
      "peso": 19.2,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 75,
      "bobina_unidades": 25,
      "bobina_rend": 151,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-107-002",
      "descripcion": "ARROZ MR. DIECK BLANCO 350 GRS (25)",
      "peso": 19.2,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "37-38",
      "tarima_div": 75,
      "bobina_unidades": 25,
      "bobina_rend": 151,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-107-004",
      "descripcion": "ARROZ BAMBI BLANCO 350 GRS (25)",
      "peso": 19.2,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 80,
      "mignon_max": 20,
      "pulido_min": "22-23",
      "tarima_div": 75,
      "bobina_unidades": 25,
      "bobina_rend": 151,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-109-001",
      "descripcion": "ARROZ MR. DIECK ESCALDADO 175 GRS (50)",
      "peso": 19.2,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 95,
      "mignon_max": 5,
      "pulido_min": "22-23",
      "tarima_div": 75,
      "bobina_unidades": 50,
      "bobina_rend": 231,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-109-002",
      "descripcion": "ARROZ MR. DIECK BLANCO 175 GRS (50)",
      "peso": 19.2,
      "unidad": "FARDO",
      "familia": "FARDO",
      "proceso": "PAQUET.",
      "entero_min": 90,
      "mignon_max": 10,
      "pulido_min": "37-38",
      "tarima_div": 80,
      "bobina_unidades": 50,
      "bobina_rend": 231,
      "granza_factor": "",
      "area": "PAQUETERIA",
      "tipo": "PT"
    },
    {
      "codigo": "PT-100-014",
      "descripcion": "ARROZ BAMBINO ECONOMICO ESCALDADO QUINTAL 100 LBS",
      "peso": 100,
      "unidad": "QUINTAL",
      "familia": "QUINTAL",
      "proceso": "M2",
      "entero_min": 87,
      "mignon_max": 13,
      "pulido_min": "22-23",
      "tarima_div": 40,
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": 1.4286,
      "area": "M2",
      "tipo": "PT"
    },
    {
      "codigo": "PT-110-001",
      "descripcion": "RECHAZO ARROZ ESCALDADO",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M2",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M2",
      "tipo": "SP"
    },
    {
      "codigo": "PT-112-001",
      "descripcion": "MIGA BLANCA",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M1",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M1",
      "tipo": "SP"
    },
    {
      "codigo": "PT-112-002",
      "descripcion": "MIGON BLANCO",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M1",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M1",
      "tipo": "SP"
    },
    {
      "codigo": "PT-112-005",
      "descripcion": "MIGON ESCALDADO",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M2",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M2",
      "tipo": "SP"
    },
    {
      "codigo": "PT-112-009",
      "descripcion": "MIGA MEMBRETADA",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M1",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M1",
      "tipo": "SP"
    },
    {
      "codigo": "PT-112-010",
      "descripcion": "MIGON ESCALDADO QUINTAL",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M2",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M2",
      "tipo": "SP"
    },
    {
      "codigo": "SP-100-002",
      "descripcion": "SEMOLINA BLANCA",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M1",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M1",
      "tipo": "SP"
    },
    {
      "codigo": "SP-100-010",
      "descripcion": "SEMOLINA ESCALDADA",
      "peso": "-",
      "unidad": "-",
      "familia": "SUBPRODUCTO",
      "proceso": "M2",
      "entero_min": "-",
      "mignon_max": "-",
      "pulido_min": "-",
      "tarima_div": "",
      "bobina_unidades": "",
      "bobina_rend": "",
      "granza_factor": "",
      "area": "M2",
      "tipo": "SP"
    }
  ],
  "orders": {
    "order|paqueteria|2026-03-28": {
      "meta": {
        "code": "PA-FO-10",
        "version": "01",
        "title": "ORDEN DIARIA DE PRODUCCIÓN PAQUETERIA",
        "note": "Programa verde de paquetería"
      },
      "notes": "TA: de sábado 28/03/2026. TB: continuar producción. Responsable según turno.",
      "sections": {
        "d1A": [
          {
            "descripcion": "ARROZ MANHATTAN ORO 1 LBS (25)",
            "codigo": "PT-106-002",
            "cantidad": 1800,
            "linea": "3",
            "envas": "2"
          },
          {
            "descripcion": "ARROZ MANHATTAN BLANCO 4 LBS (10)",
            "codigo": "PT-102-003",
            "cantidad": 720,
            "linea": "4",
            "envas": "2"
          },
          {
            "descripcion": "ARROZ MR. DIECK BLANCO 1.75 KGS (10)",
            "codigo": "PT-103-003",
            "cantidad": 800,
            "linea": "4",
            "envas": "2"
          },
          {
            "descripcion": "ARROZ MR. DIECK BLANCO 175 GRS (50)",
            "codigo": "PT-109-002",
            "cantidad": 400,
            "linea": "4",
            "envas": "2"
          }
        ],
        "d1B": [
          {
            "descripcion": "ARROZ MANHATTAN ORO 4 LBS (10)",
            "codigo": "PT-102-001",
            "cantidad": 360,
            "linea": "4",
            "envas": "2"
          },
          {
            "descripcion": "ARROZ MR. DIECK BLANCO 350 GRS (25)",
            "codigo": "PT-107-002",
            "cantidad": 2000,
            "linea": "2",
            "envas": "1"
          }
        ],
        "d2A": [
          {
            "descripcion": "ARROZ MR. DIECK BLANCO 350 GRS (25)",
            "codigo": "PT-107-002",
            "cantidad": 2000,
            "linea": "2",
            "envas": "1"
          },
          {
            "descripcion": "ARROZ MR. DIECK ESCALDADO 175 GRS (50)",
            "codigo": "PT-109-001",
            "cantidad": 800,
            "linea": "4",
            "envas": "2"
          }
        ],
        "d2B": [
          {
            "descripcion": "ARROZ MR. DIECK ESCALDADO 175 GRS (50)",
            "codigo": "PT-109-001",
            "cantidad": 1000,
            "linea": "4",
            "envas": "2"
          }
        ]
      },
      "observacion": "TA: completar marcas grandes, luego cambio a 175 gramos blanco. Asegurar 400 fardos. Luego generar cambio a Manhattan Oro 4lb."
    }
  },
  "weeklyPlans": [
    {
      "week": 13,
      "fecha": "2026-03-23",
      "codigo": "PT-103-003",
      "descripcion": "ARROZ MR. DIECK BLANCO 1.75 KGS (10)",
      "area": "PAQUETERIA",
      "programado": 1000,
      "cantidad_me": 1000,
      "tipo": "BOBINA IMPRESA"
    },
    {
      "week": 13,
      "fecha": "2026-03-23",
      "codigo": "PT-104-011",
      "descripcion": "ARROZ MANHATTAN BLANCO 1.5 KGS (10)",
      "area": "PAQUETERIA",
      "programado": 700,
      "cantidad_me": 700,
      "tipo": "BOBINA IMPRESA"
    }
  ],
  "responsables": {
    "paqueteria": [
      "Jeison Zuniga",
      "Kenner Castellanos",
      "Dennis Chavarria",
      "Walter Sagastume"
    ],
    "molino_blanco": [
      "Adelmo Suazo",
      "Jorge Vilchez",
      "Brandon Anduray"
    ],
    "molino_escaldado": [
      "Adelmo Suazo",
      "Jorge Vilchez",
      "Brandon Anduray"
    ]
  },
  "settings": {
    "packRate": 235,
    "millingRate": 100,
    "defaultEnvas": 2,
    "defaultTarima": 100
  },
  "production": []
};
